import { cp, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../../', import.meta.url));
const output = path.join(root, 'public');
const app = path.join(root, 'memory-blog');
const content = JSON.parse(await readFile(path.join(app, 'src/preview/content.generated.json'), 'utf8'));
const shell = await readFile(path.join(app, 'dist/index.html'), 'utf8');
const routes = new Map();
const escape = value => String(value).replace(/[&<>"']/g, letter => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[letter]));
const routePath = file => '/' + file.split(path.sep).join('/').replace(/index\.html$/, '');

// Keep the paths generated by Hexo, including existing article and archive links.
async function collect(directory, prefix = '') {
  for (const item of await readdir(directory, { withFileTypes: true })) {
    const relative = path.join(prefix, item.name);
    if (item.isDirectory()) await collect(path.join(directory, item.name), relative);
    else if (item.name === 'index.html') routes.set(routePath(relative), { title: content.site.name, description: content.site.description });
  }
}
await collect(output);
const titles = {
  '/': 'Yarinaoshi · Memory', '/about/': '关于我', '/archives/': '归档', '/times/': '归档',
  '/link/': '友人链', '/friends/': '友人链', '/moments/': '碎碎念', '/talk/': '碎碎念',
  '/moments/edit/': '写碎碎念', '/categories/': '分类', '/tags/': '标签'
};
for (const [url, title] of Object.entries(titles)) routes.set(url, { title, description: content.site.description });
for (const article of content.articles) {
  const metadata = { title: article.title, description: article.description };
  routes.set('/posts/' + article.id + '/', metadata);
  routes.set('/article/' + article.id + '/', metadata);
}
for (const category of content.categories) {
  routes.set('/categories/' + category + '/', { title: '分类 · ' + category, description: content.site.description });
  routes.set('/category/' + category + '/', { title: '分类 · ' + category, description: content.site.description });
}
for (const tag of content.tags) routes.set('/tags/' + tag + '/', { title: '标签 · ' + tag, description: content.site.description });
await cp(path.join(app, 'dist'), output, { recursive: true });
for (const [url, metadata] of routes) {
  const destination = path.join(output, url.slice(1), 'index.html');
  const title = url === '/' ? metadata.title : metadata.title + ' · ' + content.site.name;
  const canonical = content.site.blog + url.split('/').map(encodeURIComponent).join('/');
  const html = shell.replace(/<title>.*?<\/title>/, () => `<title>${escape(title)}</title>`)
    .replace(/<meta name="description" content="[^"]*"\s*\/>/, () => `<meta name="description" content="${escape(metadata.description)}" />`)
    .replace(/<link rel="canonical" href="[^"]*"\s*\/>/, () => `<link rel="canonical" href="${escape(canonical)}" />`);
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, html);
}
await writeFile(path.join(output, '404.html'), shell.replace('index, follow', 'noindex, follow'));
await writeFile(path.join(output, '.nojekyll'), '');
await writeFile(path.join(output, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${content.site.blog}/sitemap.xml\n`);
const sitemap = ['/','/about/','/archives/','/link/','/moments/', ...content.articles.map(article => '/posts/' + article.id + '/')];
await writeFile(path.join(output, 'sitemap.xml'), '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + sitemap.map(url => `<url><loc>${escape(content.site.blog + url)}</loc></url>`).join('') + '</urlset>\n');
await cp(path.join(app, 'LICENSE'), path.join(output, 'MEMORY-LICENSE.txt'));
console.log(`Memory site prepared at the domain root: ${routes.size} routes, ${content.articles.length} articles, ${content.moments.length} moments. Existing image and publishing assets retained.`);
